export const PRICE_UPDATE_STATUS = {
  DEPLOY: "DEPLOY_PRICE",
  FUND: "FUND_PRICE",
  REGISTER_UPKEEP: "REGISTER_PRICE_UPKEEP",
  SCHEDULE: "SCHEDULE_PRICE_UPDATE",
};

export const MINT_UPDATE_STATUS = {
  DEPLOY: "DEPLOY_MINT",
  FUND: "FUND_MINT",
  REGISTER_UPKEEP: "REGISTER_MINT_UPKEEP",
  SCHEDULE: "SCHEDULE_MINT_UPDATE",
};

export const PAUSE_UPDATE_STATUS = {
  DEPLOY: "DEPLOY_PAUSE",
  FUND: "FUND_PAUSE",
  REGISTER_UPKEEP: "REGISTER_PAUSE_UPKEEP",
  SCHEDULE: "SCHEDULE_PAUSE",
};
